name: Node.js CI

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
      - run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
        
#     strategy:
#       matrix:
#         os: [ubuntu-16.04, ubuntu-18.04]
#         node: [6, 8, 10]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
#       env:
#         CI: true
