name: TESTSTTS

on: push

env:
  SLACK_CHANNEL: CGLFL82EN
  SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
  APP: https://app.boweryvaluation.com
jobs:
  slack-notify:
    name: SN
    runs-on: ubuntu-latest
    outputs:
      thread: ${{ steps.slack.outputs.thread_ts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Post to an initial message to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          payload-file-path: .github/release-template.json

  slack-wow:
    name: WOW
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hollo world"


  ecs-deploy:
    runs-on: ubuntu-latest
    needs: build-image
    name: Deploy Webapp to ECS
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::814827541967:role/GithubOIDC-Role-QMKR3DR5WV3B
          aws-region: "us-east-1"

      - uses: Bowery-RES/action-aws-secrets@v1.1
        with:
          secrets: |
            Github/Terraform/${{ env.DEPLOYMENT_ENVIRONMENT }}/Atlas
            Github/Terraform/${{ env.DEPLOYMENT_ENVIRONMENT }}/Opensearch
          parameters: |
            /Github/Terraform/${{ env.DEPLOYMENT_ENVIRONMENT }}/WebApp_ECR_URL,
            /Github/Terraform/${{ env.DEPLOYMENT_ENVIRONMENT }}/MongoDBAtlas_Cluster_Connection_Standard_Srv,
            /Github/Terraform/${{ env.DEPLOYMENT_ENVIRONMENT }}/ECS_Cluster_Name,
            /Github/Terraform/${{ env.DEPLOYMENT_ENVIRONMENT }}/ElasticSearch_Domain_Endpoint,
            /Github/Terraform/${{ env.DEPLOYMENT_ENVIRONMENT }}/Webapp_UploadDocs_Bucket
          namespace: false
      - name: test
        run: printenv
