name: Main

on:
  push:
    branches: [master, release/v*]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "development"