name: Backmerge
# Necessary to resolve conflicts between master/release* branches asap

on:
  push:
    branches: [master]
jobs:
  release:
    name: Create GH release
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          tag: v18
          commit: ${{github.sha}}
          token: ${{ github.token }}