name: Main

on:
  workflow_dispatch:
    inputs:
      services_to_deploy:
        description: Comma separated list of services to deploy document-server=development,market-research=staging
        default: '["document-server=development","market-research=staging"]'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(github.event.inputs.services_to_deploy) }}
    steps:
      - name: Build
        run: echo "${{ matrix.service }}"
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Build
        run: echo "${{ fromJSON(needs.build) }}"
