name: Main

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["document-server=development","market-research=staging"]
    steps:
      - name: Build
        run: echo "${{ matrix.service }}"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: echo "${{ fromJSON(needs) }}"
