name: Main

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["document-server=development","market-research=staging"]
    steps:
      - name: Build
        run: echo "${{ matrix.service }}"
  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: echo "${{ needs.build.result }}"

  test:
    runs-on: ubuntu-latest
    needs: [build, check]
    steps:
      - name: Test
        run: echo "${{ needs.build.result }}"
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listJobsForWorkflowRun({
                owner: context.repo.owner,
              repo: context.repo.repo,
                run_id: context.runId
                });
              result.data.jobs.map(console.log)
              console.log(result)
