name: Backmerge
# Necessary to resolve conflicts between master/release* branches asap

on:
  push:
    branches: [master]

env:
  SLACK_CHANNEL: CGLFL82EN
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
jobs:
  release:
    name: Create GH release
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.context}}"


