name: Backmerge
# Necessary to resolve conflicts between master/release* branches asap

# on:
#   push:
#     branches: [master]
jobs:
  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          tag: v16
          commit: ${{needs.merge-release-branch.outputs.sha}}
          token: ${{ github.token }}