name: TESTSTTS

on: workflow_dispatch

env:
  SLACK_CHANNEL: CGLFL82EN
  APP: https://app.boweryvaluation.com
jobs:
  slack-notify:
    name: SN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Post to an initial message to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: ${{ env.SLACK_CHANNEL }}
          payload-file-path: .github/release-template.json
