name: TESTSTTS

on: push

jobs:
  slack-notify:
    name: SN
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Export drawio files to asciidoctor and png files
      uses: rlespinasse/drawio-export-action@v2
      with:
        path: /
        format: svg
        transparent: true
        output: drawio-assets
 