name: Main

on: push

env:
  services: "["document-server=development","market-research=staging"]"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(env.services) }}
    steps:
      - name: Build
        run: echo "${{ matrix.service }}"
